name: on-push

on:
  push:
    branches:
      - master

jobs:
  # build ng2-dragula
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - run: |
          npx nx build demo --configuration production

  # run unit tests
  unit_tests_with_coverage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - run: npx nx run-many --target=test --all --code-coverage
        continue-on-error: true

  # run linting
  linting:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - run: npm run lint
